### ISSUE TITLE
create a description of an end-to-end test

### ISSUE THREAD

**Issue by thiagomanel** [fogbow/saps-engine#108]
The purpose is to help the users to check saps engine, from submission via the dashboard (and API or DB) to archive.

We need to provide URLs to safe algorithms and known tasks to submit.

Also, it would be good to have a check of the output (both data and metadata, maybe the checksums?) And of the state of the catalog.

**Comment by thiagoyeds** [comment]
What do you suggest, sir? Submission of a processing of any task with NOP algorithms that generate any output and in the end with the download of this data generate a checksum of these outputs to compare with the expected?

**Comment by thiagomanel** [comment]
nope. the idea is to choose some tasks you already processed (from the batch we submitted for John).

The doc must describe the algorithms (docker urls) the user must configure.
The doc must describe what the user needs to do to check the output; both the output generated by the algorithm and the metadata in the catalog

**Comment by thiagomanel** [comment]
the doc could, in addition to the submission from the dashboard, show how bypass the dashboard (it is useful for the admin people)
