### ISSUE TITLE
Create CLI to send successful task email

### ISSUE THREAD

**Issue by thiagoyeds** [fogbow/saps-engine#139]
It is necessary to create a CLI that based on a SAPS task with success in processing and archived, use the path of the backend dispatcher to make it send an email with links to access the task data. This includes other things like the Openstack Object Store Service Key which must be properly configured and thereby improve the dispatcher's documentation to ensure this configuration. Besides that it is also necessary for the current version of sending email, to enable the "less secure app access" setting of the domain of the noreply email used, so you must document how to do it.

**Comment by thiagomanel** [comment]
I'm not ok with this issue. could you change it to a cli that outputs the links for finished tasks? before coding, explain here what do you plan for the cli args and the output format

**Comment by thiagoyeds** [comment]
ok @thiagomanel, I created a new issue in #145
