### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by thiagoyeds** [fogbow/saps-engine#44]
Need to create new deployment documentation for SAPS that is consistent with the new version and that a new user can do it step by step. Below is the list of documentation that should be created:

- [x]  Dashboard component
- [x]  Catalog component
- [x]  Dispatcher component
- [x]  Scheduler component
- [x]  Archiver component

**Comment by thiagomanel** [comment]
For now, we have duplicated the config files in the documentation. I think it is better for our users to have a link to the conf files and an explanation of where to find information to fill the conf (e.g. tenant and credential info for openstack stuff)
