### ISSUE TITLE
split saps-engine into different repos

### ISSUE THREAD

**Issue by thiagoyeds** [fogbow/saps-engine#63]
One repo for each component

**Comment by thiagoyeds** [comment]
@thiagomanel 
My idea is as follows:

![Untitled Diagram](https://user-images.githubusercontent.com/15807921/79363766-b6275980-7f1e-11ea-8b8c-4ff9d0382281.png)

## Saps-common repository

would have classes common to the various components such as SapsTask, SapsImage, SapsJob, SapsUser and others.

## Saps-catalog repository

would have the interface and implementations of the Catalog component, as well as the code of the Retry approach.

## Saps-dispatcher repository

everything that involves dispatcher code + backend that communicates with the Dashboard component.

## Saps-scheduler repository

everything that involves scheduler code + things related to the job execution service (Arrebol and others).

## Saps-archiver repository

everything that involves archiver code.

## Questions
About Permanent Storage, would it be put in saps-common? or a separate repository?


**Note: Shouldn't we create a SAPS organization on Github?**

**Comment by thiagomanel** [comment]
@thiagomanel I'm ok to leave the PermanentStorage in the common. This is something we can change later, if needed.

**Comment by thiagoyeds** [comment]
This issue was made
