### ISSUE TITLE
Update expired token of Swift Client

### ISSUE THREAD

**Issue by wesleymonte** [fogbow/saps-engine#94]
Currently, Swift Permanent Storage considers that the Token generated by the keystone does not expire. However, the token expires and may even be invalidated in the identity service. Therefore, it is necessary to refresh the token when trying to make a request to Swift and receive the expired token response.

**Comment by wesleymonte** [comment]
Swift's CLI allows you to receive credentials (projectId, userId, userPassword) and it is responsible for generating a token to perform the operation. Therefore, as a token is generated for each operation, we will never have an expired token in use.

**Comment by thiagoyeds** [comment]
Move to https://github.com/ufcg-lsd/saps-common/issues/12
